-- Simple Login Credentials for Propello
-- Just the essential auth users and profiles for testing

-- Create mock auth users with simple credentials
INSERT INTO auth.users (
    id,
    instance_id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    invited_at,
    confirmation_token,
    confirmation_sent_at,
    recovery_token,
    recovery_sent_at,
    email_change_token_new,
    email_change,
    email_change_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    phone,
    phone_confirmed_at,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    email_change_token_current,
    email_change_confirm_status,
    banned_until,
    reauthentication_token,
    reauthentication_sent_at,
    is_sso_user,
    deleted_at
) VALUES 
-- Sarah Johnson
(
    '11111111-1111-1111-1111-111111111111',
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    'sarah@premierrealty.com',
    '$2a$10$example_hashed_password_here',
    NOW(),
    NOW(),
    '',
    NOW(),
    '',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    '{"provider": "email", "providers": ["email"]}',
    '{"full_name": "Sarah Johnson"}',
    false,
    NOW(),
    NOW(),
    '+1-555-0101',
    NOW(),
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL,
    false,
    NULL
),
-- Michael Chen
(
    '22222222-2222-2222-2222-222222222222',
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    'michael@luxuryhomes.com',
    '$2a$10$example_hashed_password_here',
    NOW(),
    NOW(),
    '',
    NOW(),
    '',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    '{"provider": "email", "providers": ["email"]}',
    '{"full_name": "Michael Chen"}',
    false,
    NOW(),
    NOW(),
    '+1-555-0102',
    NOW(),
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL,
    false,
    NULL
)
ON CONFLICT (id) DO NOTHING;

-- Create user profiles
INSERT INTO public.user_profiles (
    user_id,
    email,
    full_name,
    company_name,
    agent_phone_number,
    agent_id,
    plan,
    is_active
) VALUES
(
    '11111111-1111-1111-1111-111111111111',
    'sarah@premierrealty.com',
    'Sarah Johnson',
    'Premier Realty Group',
    '+1-555-0101',
    'SARAH-J-2024',
    'premium',
    true
),
(
    '22222222-2222-2222-2222-222222222222',
    'michael@luxuryhomes.com',
    'Michael Chen',
    'Luxury Homes Realty',
    '+1-555-0102',
    'MICHAEL-C-2024',
    'premium',
    true
)
ON CONFLICT (email) DO NOTHING;
